server:
  port: 8004

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  cloud:
    zookeeper:
      connect-string: 192.168.253.129:2181

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.smj.entities.Payment


upload:
  qiniu:
    domain: "https://cdn-ssl.meb.com"
    access-key: "vECq3gaU9nYuFCg5-XPf8vG5ia0I55XHFhFN_bYO"
    secret-key: "HLO0bvRW0rwSDHV5J3slQ4-zbtY_OTOjTAjZMrLu"
    bucket: "meb-com"
