server:
  port: 9527
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #路由的id，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001 #匹配后提供的路由地址
          predicates:
            - Path=/payment/get/**  #断言，路径匹配的进行路由

        - id: payment_routh2
          uri: http://localhost:8001
          predicates:
            - Path=/payment/lb/**
