server:
  port: 80


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
    register-with-eureka: false

#设置ribbon客户端超时时间，openfeign默认支持ribbon
ribbon:
#指的是建立连接所需要的时间，适用于网络状况较差的情况，两端连接所需要的时间
  ReadTimeout: 5000
#指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000
logging:
  level:
#    feign日志以什么级别监控哪个接口
    com.smj.service.PaymentFeignService: debug
